name: Containerlab Deployment

on:
  workflow_dispatch:  # allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v5

      - name: Install Containerlab
        run: |
          curl -sSL https://get.containerlab.dev | sudo bash

      - name: Deploy Containerlab topology
        run: |
          sudo clab deploy -t containerlab/vyos.clab.yml

      - name: Show deployed nodes
        run: |
          sudo clab inspect -t containerlab/vyos.clab.yml

      - name: Destroy Containerlab topology
        run: |
          sudo clab destroy -t containerlab/vyos.clab.yml
